### ISSUE TITLE
Start block missed in BlockIterator

### ISSUE THREAD

**Issue by Deathinflames** [UtechtDustin/Builder-s-Wand#45] opened 2019-09-03 16:33 UTC
Hello, i noticed this in the console and couldn't find an existing ticket for it.

https://pastebin.com/raw/vdapU2At

Thanks!

This server is running Paper version git-Paper-639 (MC: 1.13.2)

**Comment by UtechtDustin** [comment] 2020-08-30 17:38
I close this issue, because i cant reproduce it.
Also the issue almost 1 year old.

**Closed by UtechtDustin** 2020-08-30 17:38 UTC
