### ISSUE TITLE
BuildersWand generates an exception randonly

### ISSUE THREAD

**Issue by wiilover22** [UtechtDustin/Builder-s-Wand#59] opened 2021-05-29 20:37 UTC
Not sure what triggers it, as it happens completly randomly, and has nothing to do with even having the wand in your hand/being used. I could be mining somewhere, with the wand nowhere in sight and still see this error in the log.

`[21:46:18] [Server thread/WARN]: [BuildersWand] Task #3180 for BuildersWand v2.18.0 generated an exception
java.lang.IllegalStateException: Start block missed in BlockIterator
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:171) ~[patched_1.16.5.jar:git-Paper-651]
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:236) ~[patched_1.16.5.jar:git-Paper-651]
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:277) ~[patched_1.16.5.jar:git-Paper-651]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.getLineOfSight(CraftLivingEntity.java:188) ~[patched_1.16.5.jar:git-Paper-651]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.getTargetBlock(CraftLivingEntity.java:210) ~[patched_1.16.5.jar:git-Paper-651]
	at de.False.BuildersWand.events.WandEvents$1.run(WandEvents.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-651]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-651]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Paper-651]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-651]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-651]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-651]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-651]
	at java.lang.Thread.run(Thread.java:829) [?:?]`

**Comment by UtechtDustin** [comment] 2021-06-03 02:27
How often do you get that exception ?
I'm not able to reproduce it right know.

**Comment by wiilover22** [comment] 2021-06-03 03:27
Not often. I have no idea how to reproduce it, since as I said - it happens extremely randomly. I can be the only one online in the server, with no wand in my inventory, and sometimes the error happens once - and sometimes I've seen it spam the log 10+ times in a row.

I wish I could give you more information, but there's no rhyme or nor reason as to why the error occurs. I'll do my best to monitor my server and see if I can figure out some form of correlation.

**Comment by UtechtDustin** [comment] 2021-06-03 18:00
Okay, thanks for the infromation.
I will try to reproduce it!

**Comment by johnneijzen** [comment] 2021-06-05 12:02
i just happen to me too now I just update my builder and update to java 16 and if try shift-click item up or down in inventory it wont move and spam same error and when I remove it builderwand it issue is gone

**Comment by UtechtDustin** [comment] 2021-06-05 14:31
> i just happen to me too now I just update my builder and update to java 16 and if try shift-click item up or down in inventory it won't move also no builder wand in inventory and spam the same error and when I remove it builderwand plugin and it issue is gone

Fixed the issue with the shift click in the newest version, but the error message is a different then reported from @wiilover22

**Comment by johnneijzen** [comment] 2021-06-05 16:11
okay thanks

**Comment by UtechtDustin** [comment] 2022-01-11 22:29
Should be fixed in the newest version.

**Closed by UtechtDustin** 2022-01-11 22:29 UTC
