### ISSUE TITLE
Error on enabling, possibly because of Java 16?

### ISSUE THREAD

**Issue by blek-id** [UtechtDustin/Builder-s-Wand#65] opened 2021-07-02 14:45 UTC
Hi, I've updated my server's Java version to Java 16 in preparation for 1.17,
one thing I noticed is that BuilderWands now wouldn't load properly, here is the only log that I could provide

```
[04:01:54] [Server thread/INFO]: [BuildersWand] Enabling BuildersWand v2.18.4
[04:01:55] [Server thread/INFO]: [BuildersWand] Looking for updates...
[04:01:55] [Server thread/INFO]: [BuildersWand] Plugin is up-to-date
[04:01:55] [Server thread/ERROR]: Error occurred while enabling BuildersWand v2.18.4 (Is it up to date?)
java.lang.NullPointerException: null
	at de.False.BuildersWand.manager.InventoryManager.load(InventoryManager.java:41) ~[?:?]
	at de.False.BuildersWand.Main.loadConfigFiles(Main.java:103) ~[?:?]
	at de.False.BuildersWand.Main.onEnable(Main.java:61) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-575]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-575]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-575]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-575]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-575]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[04:01:55] [Server thread/INFO]: [BuildersWand] Disabling BuildersWand v2.18.4
```

Any clue how to fix this?

**Comment by UtechtDustin** [comment] 2021-07-02 19:15
I don't think its because of java 16, could it possible that you changed the inventory size of the wand?

**Comment by blek-id** [comment] 2021-07-08 05:13
I did change the inventory size of the wand, is it not allowed to do so?

```
wands:
  '1':
    name: '&3Builders Wand'
    material: BLAZE_ROD
    maxSize: 8
    consumeItems: true
    durability:
      amount: 130
      enabled: false
      text: '&5Durability: &e{durability}'
    crafting:
      ingredient:
        d: DIAMOND
        b: BLAZE_ROD
      enabled: false
      shapeless: false
      recipe:
      - xxd
      - xbx
      - bxx
    particles:
      enabled: true
      type: FLAME
      count: 1
    storage:
      enabled: true
      size: 54
```

**Comment by UtechtDustin** [comment] 2021-07-09 10:34
The Problem is the saved content of the iventories, because theire have a other size of the inventory now.
This bug will be fixed in the a further version, for now you have to options:
- Change back the size
- Delete de inventories contenst (plugins/BuildersWand/storage)

**Closed by UtechtDustin** 2021-07-09 10:34 UTC
